name: CI
on:
    push:
    pull_request:
jobs:
    commit-check:
        name: Check Conventional Commit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check Conventional Commit
              uses: webiny/action-conventional-commits@v1.1.0
    markdown-link-check:
        name: Check Markdown Links
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check markdown links
              uses: gaurav-nelson/github-action-markdown-link-check@v1
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
            - name: Install dependencies
              run: npm ci --ignore-scripts

            - name: Build
              run: npm run build
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
            - name: Install dependencies
              run: npm ci --ignore-scripts

            - name: Lint
              run: npm run lint
            - name: Format
              run: npm run format
    test:
        name: Test
        runs-on: ubuntu-latest
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
            - name: Install dependencies
              run: npm ci --ignore-scripts

            - name: Test (With Coverage)
              run: npm run test:coverage

            - name: Upload test artifacts
              uses: actions/upload-artifact@v3
              if: success() || failure() # run this step even if previous step failed
              with:
                  name: test-results
                  path: test/junit.xml
            - name: Upload coverage artifacts
              uses: actions/upload-artifact@v3
              if: success() || failure() # run this step even if previous step failed
              with:
                  name: test-coverage
                  path: coverage/cobertura-coverage.xml

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
            - name: Upload coverage reports to Codeclimate
              uses: paambaati/codeclimate-action@v4.0.0
              env:
                  CC_TEST_REPORTER_ID: 58fee0878c31e85a459cb081232fb69f843bf41b49d4ddf5bfd89373bbba0e81
              with:
                  coverageLocations: |
                      coverage/cobertura-coverage.xml:cobertura
